name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_RSA_KEY }}

      - name: SSH into Azure server and execute commands
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa smplcqa@20.246.40.123 << 'EOF'
            cd smplc/backend/GenAI
            sudo git status
            sudo git pull | grep "luv2001" | grep "luv2002"

