name : Simple Workflow

on :
  push :
    branches :
      - main

jobs :
  build:
    runs-on : ubuntu-latest
    steps:
      - name : Print a statement
        run : echo "Hey there .. I am using whatsapp"