name : Simple Workflow

on :
  push :
    branches :
      - main

jobs :
  build:
    runs-on : ubuntu-latest
    steps:
      - name : checking the directory
        run : ls

      - uses : actions/checkout@v4
      - name : "git checkout action"
        run : ls